# Generated by Django 5.0.6 on 2024-07-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('lancamento', models.DateField()),
                ('plataforma', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_jogos/')),
            ],
        ),
    ]
