# Generated by Django 5.0.6 on 2024-07-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/'),
        ),
    ]
